### ISSUE TITLE
Prompt label always has display: inline style

### ISSUE THREAD

**Issue by ovk** [chrisdone/jquery-console#51]
Prompt label always has inline style `display: inline`:

```
<span class="jquery-console-prompt-label" style="display: inline;"></span>
```

However, sometimes it can be useful to set it to `inline-block`; for instance, to apply fixed width to it, so `jquery-console-message` can be aligned with `jquery-console-prompt-label`.

It seem like the issue comes from using `show()` method on `label` in the `newPromptBox` function:

```
promptBox.append(label.text(labelText).show());
```

which implicitly adds `display: inline` style.

**Comment by chrisdone** [comment]
PR welcome!
